server:
  port: 9991


spring:
  application:
    name: demo

#===================================rocketmq======================
rocketmq:
  producer: ###producer
    isOnOff: on   #该应用是否启用生产者
    groupName: ${spring.application.name}_xxx_topic  #发送同一类消息的设置为同一个group，保证唯一,默认不需要设置，rocketmq会使用ip@pid(pid代表jvm名字)作为唯一标示
    namesrvAddr: 192.168.0.38:9876;192.168.0.39:9876   #mq的nameserver地址
    maxMessageSize: 4096   #消息最大长度 默认1024*4(4M)
    sendMsgTimeout: 3000 #发送消息超时时间,默认3000
    retryTimesWhenSendFailed: 2  #发送消息失败重试次数，默认2


  rocketmq:
    producer: ###producer
      isOnOff: on   #该应用是否启用生产者
      groupName: ${spring.application.name}  #发送同一类消息的设置为同一个group，保证唯一,默认不需要设置，rocketmq会使用ip@pid(pid代表jvm名字)作为唯一标示
      namesrvAddr: 192.168.0.38:9876;192.168.0.39:9876   #mq的nameserver地址
      maxMessageSize: 4096   #消息最大长度 默认1024*4(4M)
      sendMsgTimeout: 3000 #发送消息超时时间,默认3000
      retryTimesWhenSendFailed: 2  #发送消息失败重试次数，默认2
#    consumer: ###consumer
#      isOnOff: on #该应用是否启用消费者
#      namesrvAddr: 192.168.0.38:9876;192.168.0.39:9876    #mq的nameserver地址
#      consumeThreadMin: 20
#      consumeThreadMax: 64
#      consumeMessageBatchMaxSize: 1 #设置一次消费消息的条数，默认为1条
#      goodsTopics: xxx_topic~*;  #该消费者订阅的主题和tags("*"号表示订阅该主题下所有的tags),格式：topic~tag1||tag2||tag3;topic2~*;
#      goodsGroupName: ${spring.application.name}-goods
#      shopTopics: xxx_info_topic~*;  #该消费者订阅的主题和tags("*"号表示订阅该主题下所有的tags),格式：topic~tag1||tag2||tag3;topic2~*;
#      shopGroupName: ${spring.application.name}-shop