server:
  port: 9991
spring:
  application:
    name: demo

#===================================rocketmq======================
rocketmq:
  producer:
    isOnOff: on
    groupName: ${spring.application.name}_xxx_topic
    groupNameTrans: ${spring.application.name}_trans_topic
    namesrvAddr: 192.168.0.38:9876;192.168.0.39:9876
    maxMessageSize: 4096
    sendMsgTimeout: 3000
    retryTimesWhenSendFailed: 2
    testTopic: TopicTest
    testTopicTrans: liutong_test_topic