server:
  port: 9997


spring:
  application:
    name: demo-service-lt

#================================= eureka 相关配置 ====================================
eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.32:8761/eureka/,http://192.168.0.33:8761/eureka/,http://192.168.0.34:8761/eureka/

#================================= swagger 相关配置 ====================================
swagger:
  base-package: com.example.demo
  title: service timeout
  description: xxx系统。
  version: 1.0
  contact:
    name: xxxx
    email: 123@qq.com
  enabled: true
  authorization:
    key-name: loginToken
# 解决swagger报空异常
logging:
  level:
    io.swagger.models.parameters.AbstractSerializableParameter: error


